using static AdventOfCode2025.Client.Days.Day07.Solver;

namespace AdventOfCode2025.Client.Days.Day07;

public class SolverTests
{
    public Solver GetUnit()
    {
        return new();
    }

    [Fact]
    public void Part1_Test_0()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        Solver unit = GetUnit();


        // Act
        TachyonManifolds tachyonManifolds = new(input);

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_1()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            .......|.......
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        Solver unit = GetUnit();
        TachyonManifolds tachyonManifolds = new(input);

        // Act
        tachyonManifolds.Step();

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_2()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            .......|.......
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            .......|.......
            ......|^|......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        Solver unit = GetUnit();
        TachyonManifolds tachyonManifolds = new(input, 1);

        // Act
        tachyonManifolds.Step();

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_3()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            .......|.......
            ......|^|......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            .......|.......
            ......|^|......
            ......|.|......
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        Solver unit = GetUnit();
        TachyonManifolds tachyonManifolds = new(input, 2);

        // Act
        tachyonManifolds.Step();

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_4()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            .......|.......
            ......|^|......
            ......|.|......
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            .......|.......
            ......|^|......
            ......|.|......
            .....|^|^|.....
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

        Solver unit = GetUnit();
        TachyonManifolds tachyonManifolds = new(input, 3);

        // Act
        tachyonManifolds.Step();

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_5()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        string expected = """
            .......S.......
            .......|.......
            ......|^|......
            ......|.|......
            .....|^|^|.....
            .....|.|.|.....
            ....|^|^|^|....
            ....|.|.|.|....
            ...|^|^|||^|...
            ...|.|.|||.|...
            ..|^|^|||^|^|..
            ..|.|.|||.|.|..
            .|^|||^||.||^|.
            .|.|||.||.||.|.
            |^|^|^|^|^|||^|
            |.|.|.|.|.|||.|
            """;


        TachyonManifolds tachyonManifolds = new(input);

        // Act
        while (tachyonManifolds.CanStep())
        {
            tachyonManifolds.Step();
            string s = tachyonManifolds.ToString();
        }

        // Assert
        Assert.Equal(expected, tachyonManifolds.ToString());
    }

    [Fact]
    public void Part1_Test_6()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("1", result);
    }

    [Fact]
    public void Part1_Test_7()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("3", result);
    }

    [Fact]
    public void Part1_Test_8()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("6", result);
    }

    [Fact]
    public void Part1_Test_9()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("9", result);
    }

    [Fact]
    public void Part1_Test_10()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("13", result);
    }

    [Fact]
    public void Part1_Test_11()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("16", result);
    }

    [Fact]
    public void Part1_Test_12()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("21", result);
    }








    [Fact]
    public void Part2_Test_6()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("2", result);
    }

    [Fact]
    public void Part2_Test_7()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("4", result);
    }

    [Fact]
    public void Part2_Test_8()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("8", result);
    }

    [Fact]
    public void Part2_Test_9()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("18", result);
    }

    [Fact]
    public void Part2_Test_10()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("31", result);
    }

    [Fact]
    public void Part2_Test_11()
    {
        // Arrange
        IEnumerable<string> input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """.Split(Environment.NewLine);

        Solver unit = GetUnit();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("40", result);
    }













    [Fact]
    public async Task Part1()
    {
        // Arrange
        Solver unit = GetUnit();
        string[] input = await unit.GetInputsAsync();

        // Act
        string result = unit.Solve1(input);

        // Assert
        Assert.Equal("1539", result);
    }

    [Fact]
    public async Task Part2()
    {
        // Arrange
        Solver unit = GetUnit();
        string[] input = await unit.GetInputsAsync();

        // Act
        string result = unit.Solve2(input);

        // Assert
        Assert.Equal("NotImplemented", result);
    }
}
